-- =========================================================
-- Sample seed data - 12 categories, 120 products
-- Run AFTER ecommerce.sql
-- =========================================================

USE ecommerce;

INSERT INTO categories (name, slug) VALUES
    ('Tech & Gadgets', 'tech-gadgets'),
    ('Fashion & Apparel', 'fashion-apparel'),
    ('Home & Living', 'home-living'),
    ('Beauty & Wellness', 'beauty-wellness'),
    ('Sports & Fitness', 'sports-fitness'),
    ('Entertainment & Media', 'entertainment-media'),
    ('Office Essentials', 'office-essentials'),
    ('Health & Nutrition', 'health-nutrition'),
    ('Auto & Vehicles', 'auto-vehicles'),
    ('Pets & Animals', 'pets-animals'),
    ('Garden & Outdoor', 'garden-outdoor'),
    ('Food & Beverages', 'food-beverages');

-- Admin login: admin@example.com / admin123
-- Demo customer: customer@example.com / admin123
INSERT INTO users (name, email, password_hash, role) VALUES
    ('Admin', 'admin@example.com', '$2b$10$zXkXDK6ilT8JaUYlp/SsouHsFCN27rjmPo3gsIS0s4q6gB0LQWOH2', 'admin'),
    ('Test Customer', 'customer@example.com', '$2b$10$zXkXDK6ilT8JaUYlp/SsouHsFCN27rjmPo3gsIS0s4q6gB0LQWOH2', 'customer');

INSERT INTO products (category_id, name, slug, description, price, compare_at_price, stock, image, is_active) VALUES
(1, 'Ultra Slim Laptop 15"', 'ultra-slim-laptop-15-1', 'A lightweight aluminum-body laptop built for all-day productivity, with a crisp 15-inch display and fast SSD storage.', 799.00, 962.80, 12, 'seed-001.svg', 1),
(1, 'Pro Wireless Earbuds', 'pro-wireless-earbuds-2', 'True wireless earbuds with active noise cancellation and a compact charging case that fits in any pocket.', 129.00, 150.99, 18, 'seed-002.svg', 1),
(1, '4K Action Camera', '4k-action-camera-3', 'Waterproof action camera that captures smooth 4K footage, built for hikes, rides, and everything in between.', 189.00, 233.30, 50, 'seed-003.svg', 1),
(1, 'Smart Fitness Watch', 'smart-fitness-watch-4', 'Tracks heart rate, sleep, and workouts, with a battery that lasts up to seven days on a single charge.', 149.00, 178.28, 8, 'seed-004.svg', 1),
(1, 'Portable Power Bank 20000mAh', 'portable-power-bank-20000mah-5', 'A pocketable charger with enough capacity for multiple full phone charges on the go.', 39.00, NULL, 8, 'seed-005.svg', 1),
(1, 'Mechanical Gaming Keyboard', 'mechanical-gaming-keyboard-6', 'Hot-swappable switches and per-key RGB lighting, built for long sessions and fast response.', 89.00, NULL, 50, 'seed-006.svg', 1),
(1, 'Wireless Charging Pad', 'wireless-charging-pad-7', 'A slim charging pad that powers up compatible phones and earbuds without the cable clutter.', 24.00, NULL, 40, 'seed-007.svg', 1),
(1, 'Bluetooth Portable Speaker', 'bluetooth-portable-speaker-8', 'Compact speaker with surprisingly deep bass, rated for splashes and built for backyard afternoons.', 59.00, NULL, 8, 'seed-008.svg', 1),
(1, 'Smart Home Hub', 'smart-home-hub-9', 'The central point for lights, locks, and sensors, with voice control and a simple mobile app.', 79.00, NULL, 15, 'seed-009.svg', 1),
(1, 'Noise-Cancelling Headphones', 'noise-cancelling-headphones-10', 'Over-ear headphones that quiet the world down to just your music, with 30-hour battery life.', 179.00, NULL, 25, 'seed-010.svg', 1),
(2, 'Classic Wool Sweater', 'classic-wool-sweater-11', 'A soft merino-blend sweater with a timeless crew neck, made to layer through the cold months.', 68.00, NULL, 18, 'seed-011.svg', 1),
(2, 'Slim Fit Chinos', 'slim-fit-chinos-12', 'Everyday chinos with a bit of stretch, tailored for a clean line without feeling stiff.', 45.00, 55.17, 25, 'seed-012.svg', 1),
(2, 'Running Shoes - Men''s', 'running-shoes-men-s-13', 'Lightweight cushioned trainers built for daily miles, with breathable mesh uppers.', 95.00, NULL, 25, 'seed-013.svg', 1),
(2, 'Running Shoes - Women''s', 'running-shoes-women-s-14', 'A responsive foam midsole and snug knit upper designed for tempo runs and long weekends.', 95.00, NULL, 20, 'seed-014.svg', 1),
(2, 'Denim Trucker Jacket', 'denim-trucker-jacket-15', 'A wardrobe staple in mid-wash denim, built to soften and fade beautifully with wear.', 74.00, NULL, 40, 'seed-015.svg', 1),
(2, 'Everyday Leather Belt', 'everyday-leather-belt-16', 'Full-grain leather belt with a simple brushed buckle, built to outlast the jeans it''s paired with.', 32.00, 38.68, 30, 'seed-016.svg', 1),
(2, 'Cotton Crew T-Shirt (3-Pack)', 'cotton-crew-t-shirt-3-pack-17', 'Soft combed cotton tees in a classic fit, the kind you reach for every single week.', 28.00, NULL, 25, 'seed-017.svg', 1),
(2, 'Packable Rain Jacket', 'packable-rain-jacket-18', 'A featherweight shell that folds into its own pocket, ready for the forecast that changes on you.', 58.00, 69.34, 12, 'seed-018.svg', 1),
(2, 'Wool Blend Scarf', 'wool-blend-scarf-19', 'A generously sized scarf in a soft wool blend, warm without the bulk.', 26.00, NULL, 20, 'seed-019.svg', 1),
(2, 'Canvas Sneakers', 'canvas-sneakers-20', 'Low-profile canvas sneakers with a rubber sole built for city sidewalks and long walks.', 42.00, NULL, 18, 'seed-020.svg', 1),
(3, 'Cordless Stick Vacuum', 'cordless-stick-vacuum-21', 'A lightweight cordless vacuum with strong suction and a detachable handheld unit for stairs and corners.', 189.00, NULL, 30, 'seed-021.svg', 1),
(3, 'Ceramic Cookware Set (5-Piece)', 'ceramic-cookware-set-5-piece-22', 'A non-stick ceramic-coated set that goes from stovetop to table without the harsh chemical coating.', 129.00, 157.52, 25, 'seed-022.svg', 1),
(3, 'Memory Foam Pillow', 'memory-foam-pillow-23', 'A contoured pillow that keeps its shape night after night, easing pressure on neck and shoulders.', 34.00, NULL, 20, 'seed-023.svg', 1),
(3, 'Aromatherapy Diffuser', 'aromatherapy-diffuser-24', 'A quiet ultrasonic diffuser with color-changing light, built to fill a room with scent in minutes.', 29.00, NULL, 12, 'seed-024.svg', 1),
(3, 'Stainless Steel Water Bottle', 'stainless-steel-water-bottle-25', 'Double-walled insulation keeps drinks cold for 24 hours or hot for 12, in a bottle built to last.', 22.00, NULL, 15, 'seed-025.svg', 1),
(3, 'Linen Throw Blanket', 'linen-throw-blanket-26', 'A breathable linen-cotton blend blanket, equally at home on the sofa or the end of the bed.', 44.00, 53.94, 18, 'seed-026.svg', 1),
(3, 'LED Desk Lamp with USB Port', 'led-desk-lamp-with-usb-port-27', 'Adjustable brightness and color temperature, plus a built-in USB port for charging while you work.', 27.00, NULL, 50, 'seed-027.svg', 1),
(3, 'Bamboo Cutting Board Set', 'bamboo-cutting-board-set-28', 'Three sizes of sustainably sourced bamboo boards, gentle on knife edges and easy to clean.', 33.00, NULL, 25, 'seed-028.svg', 1),
(3, 'Robot Vacuum Cleaner', 'robot-vacuum-cleaner-29', 'Maps your home automatically and returns to its dock to recharge, so the floors stay clean without the effort.', 249.00, NULL, 8, 'seed-029.svg', 1),
(3, 'Scented Soy Candle Set', 'scented-soy-candle-set-30', 'Three hand-poured soy candles in warm seasonal scents, each burning cleanly for 40+ hours.', 25.00, NULL, 8, 'seed-030.svg', 1),
(4, 'Vitamin C Facial Serum', 'vitamin-c-facial-serum-31', 'A lightweight brightening serum formulated to even skin tone and soften the look of fine lines.', 32.00, NULL, 30, 'seed-031.svg', 1),
(4, 'Bamboo Charcoal Face Mask', 'bamboo-charcoal-face-mask-32', 'A deep-cleansing clay mask that draws out impurities without stripping the skin.', 18.00, NULL, 18, 'seed-032.svg', 1),
(4, 'Electric Facial Cleansing Brush', 'electric-facial-cleansing-brush-33', 'Gentle sonic vibrations lift away makeup and buildup better than fingers alone.', 39.00, NULL, 25, 'seed-033.svg', 1),
(4, 'Argan Oil Hair Treatment', 'argan-oil-hair-treatment-34', 'A lightweight oil that tames frizz and adds shine without weighing hair down.', 21.00, NULL, 40, 'seed-034.svg', 1),
(4, 'Natural Deodorant (3-Pack)', 'natural-deodorant-3-pack-35', 'Aluminum-free deodorant in three scents, formulated to go on smooth and last all day.', 19.00, 22.38, 40, 'seed-035.svg', 1),
(4, 'Jade Facial Roller', 'jade-facial-roller-36', 'A cooling facial massage tool that helps de-puff and relax tense skin in a few minutes.', 16.00, NULL, 50, 'seed-036.svg', 1),
(4, 'Lavender Bath Salts', 'lavender-bath-salts-37', 'Epsom salts infused with real lavender oil, made for the bath that ends a long day.', 14.00, NULL, 30, 'seed-037.svg', 1),
(4, 'Matte Lipstick Set (4-Pack)', 'matte-lipstick-set-4-pack-38', 'Four long-wearing shades that go from everyday neutral to evening bold.', 26.00, NULL, 30, 'seed-038.svg', 1),
(4, 'Electric Nail File Kit', 'electric-nail-file-kit-39', 'A rechargeable manicure set with interchangeable heads for shaping, buffing, and polishing.', 24.00, NULL, 15, 'seed-039.svg', 1),
(4, 'Hyaluronic Acid Moisturizer', 'hyaluronic-acid-moisturizer-40', 'A rich daily moisturizer that locks in hydration without feeling greasy under makeup.', 28.00, NULL, 12, 'seed-040.svg', 1),
(5, 'Adjustable Dumbbell Set', 'adjustable-dumbbell-set-41', 'A space-saving pair of dumbbells that adjust from 5 to 52.5 lbs each with a simple dial.', 299.00, 353.42, 12, 'seed-041.svg', 1),
(5, 'Yoga Mat with Carry Strap', 'yoga-mat-with-carry-strap-42', 'Extra-thick non-slip cushioning, sized generously for taller practitioners.', 34.00, NULL, 30, 'seed-042.svg', 1),
(5, 'Resistance Bands Set (5-Piece)', 'resistance-bands-set-5-piece-43', 'Five resistance levels in one set, ideal for strength work at home or on the road.', 22.00, NULL, 30, 'seed-043.svg', 1),
(5, 'Insulated Sports Water Bottle', 'insulated-sports-water-bottle-44', 'A leak-proof bottle with a wide mouth for ice, built to survive gym bags and trail runs alike.', 19.00, NULL, 40, 'seed-044.svg', 1),
(5, 'Foam Roller', 'foam-roller-45', 'A firm-density roller for post-workout recovery, easing tight muscles after leg day.', 24.00, NULL, 50, 'seed-045.svg', 1),
(5, 'Jump Rope with Ball Bearings', 'jump-rope-with-ball-bearings-46', 'A speed rope built for smooth, fast rotations and interval training.', 15.00, NULL, 8, 'seed-046.svg', 1),
(5, 'Adjustable Weight Bench', 'adjustable-weight-bench-47', 'Folds flat for storage and adjusts through multiple incline positions for a full home gym.', 119.00, NULL, 12, 'seed-047.svg', 1),
(5, 'Cycling Gloves', 'cycling-gloves-48', 'Padded palms and breathable backs, built for long rides and better bar grip.', 18.00, NULL, 50, 'seed-048.svg', 1),
(5, 'Camping Hammock', 'camping-hammock-49', 'A packable double-layer hammock rated for two, with included tree straps.', 36.00, 44.53, 25, 'seed-049.svg', 1),
(5, 'Hiking Backpack 30L', 'hiking-backpack-30l-50', 'A trail-ready pack with a padded hip belt and hydration bladder compartment.', 74.00, 95.79, 40, 'seed-050.svg', 1),
(6, 'Bluetooth Turntable', 'bluetooth-turntable-51', 'A modern record player with built-in speakers and wireless streaming to any Bluetooth speaker.', 149.00, NULL, 20, 'seed-051.svg', 1),
(6, 'Board Game Night Bundle', 'board-game-night-bundle-52', 'Three classic strategy games in one bundle, built for family game nights.', 54.00, NULL, 15, 'seed-052.svg', 1),
(6, 'Wireless Gaming Controller', 'wireless-gaming-controller-53', 'A responsive controller with programmable buttons and a 20-hour battery life.', 49.00, NULL, 12, 'seed-053.svg', 1),
(6, 'Streaming Media Player', 'streaming-media-player-54', 'Plug-and-play 4K streaming stick with voice remote and access to every major app.', 39.00, NULL, 20, 'seed-054.svg', 1),
(6, 'Puzzle 1000-Piece Landscape', 'puzzle-1000-piece-landscape-55', 'A beautifully illustrated 1000-piece puzzle, the kind that takes over the dining table for a weekend.', 17.00, NULL, 50, 'seed-055.svg', 1),
(6, 'Portable Projector', 'portable-projector-56', 'A compact home projector for movie nights on any blank wall, indoors or out.', 189.00, NULL, 15, 'seed-056.svg', 1),
(6, 'Acoustic Guitar - Beginner Set', 'acoustic-guitar-beginner-set-57', 'A full-size acoustic guitar bundled with a gig bag, tuner, and picks to get started right away.', 129.00, NULL, 15, 'seed-057.svg', 1),
(6, 'Graphic Novel Collector''s Set', 'graphic-novel-collector-s-set-58', 'A three-volume boxed set that reads as a complete story arc from start to finish.', 42.00, NULL, 50, 'seed-058.svg', 1),
(6, 'Retro Arcade Mini Console', 'retro-arcade-mini-console-59', 'Pre-loaded with dozens of classic games, plugged straight into any modern TV.', 59.00, NULL, 25, 'seed-059.svg', 1),
(6, 'Noise-Isolating Gaming Headset', 'noise-isolating-gaming-headset-60', 'Clear positional audio and a detachable mic, built for long multiplayer sessions.', 69.00, NULL, 12, 'seed-060.svg', 1),
(7, 'Ergonomic Mesh Office Chair', 'ergonomic-mesh-office-chair-61', 'Breathable mesh back and adjustable lumbar support, built for long days at the desk.', 179.00, NULL, 20, 'seed-061.svg', 1),
(7, 'Standing Desk Converter', 'standing-desk-converter-62', 'Sits on top of any desk and lifts smoothly between sitting and standing positions.', 149.00, NULL, 18, 'seed-062.svg', 1),
(7, 'Wireless Mouse and Keyboard Combo', 'wireless-mouse-and-keyboard-combo-63', 'A clean, cable-free desk setup with a keyboard quiet enough for shared offices.', 34.00, 42.40, 12, 'seed-063.svg', 1),
(7, 'Desk Organizer Set', 'desk-organizer-set-64', 'Modular trays and holders that keep pens, cables, and notes exactly where you left them.', 22.00, NULL, 12, 'seed-064.svg', 1),
(7, 'Dot Grid Notebook (3-Pack)', 'dot-grid-notebook-3-pack-65', '120 gsm dot-grid pages that resist ink bleed-through, in a size that fits any bag.', 16.00, NULL, 50, 'seed-065.svg', 1),
(7, 'Adjustable Laptop Stand', 'adjustable-laptop-stand-66', 'Raises a laptop to eye level and improves airflow, foldable flat for travel.', 29.00, NULL, 15, 'seed-066.svg', 1),
(7, 'Desk Lamp with Wireless Charger', 'desk-lamp-with-wireless-charger-67', 'A dimmable LED lamp with a built-in charging pad hidden in the base.', 36.00, 45.20, 50, 'seed-067.svg', 1),
(7, 'Whiteboard Calendar Planner', 'whiteboard-calendar-planner-68', 'A dry-erase monthly planner sized for a wall, built for teams that plan out loud.', 24.00, NULL, 30, 'seed-068.svg', 1),
(7, 'Executive Fountain Pen Set', 'executive-fountain-pen-set-69', 'A weighted fountain pen with a smooth nib, boxed with a spare ink cartridge.', 32.00, NULL, 50, 'seed-069.svg', 1),
(7, 'Document Shredder', 'document-shredder-70', 'A quiet cross-cut shredder rated for a small office''s daily paper load.', 44.00, NULL, 18, 'seed-070.svg', 1),
(8, 'Whey Protein Powder 2lb', 'whey-protein-powder-2lb-71', '24g of protein per scoop in a smooth, easy-mixing formula, unflavored and flavored options.', 34.00, NULL, 30, 'seed-071.svg', 1),
(8, 'Daily Multivitamin (90-Count)', 'daily-multivitamin-90-count-72', 'A once-daily multivitamin covering the essentials, easy to swallow and gentle on the stomach.', 19.00, NULL, 25, 'seed-072.svg', 1),
(8, 'Omega-3 Fish Oil Softgels', 'omega-3-fish-oil-softgels-73', 'Purified fish oil softgels with no aftertaste, sourced and tested for purity.', 17.00, NULL, 50, 'seed-073.svg', 1),
(8, 'Digital Kitchen Food Scale', 'digital-kitchen-food-scale-74', 'Precise gram measurements for portioning meals and following recipes exactly.', 15.00, NULL, 18, 'seed-074.svg', 1),
(8, 'Herbal Sleep Tea (30-Bag Box)', 'herbal-sleep-tea-30-bag-box-75', 'A caffeine-free blend of chamomile and valerian root, steeped for the wind-down before bed.', 12.00, 15.13, 25, 'seed-075.svg', 1),
(8, 'Electrolyte Hydration Mix', 'electrolyte-hydration-mix-76', 'A low-sugar electrolyte powder for workouts, travel days, or just staying ahead of dehydration.', 18.00, 23.25, 18, 'seed-076.svg', 1),
(8, 'Adjustable Posture Corrector', 'adjustable-posture-corrector-77', 'A lightweight brace that gently reminds the shoulders back during long desk hours.', 21.00, NULL, 8, 'seed-077.svg', 1),
(8, 'Blood Pressure Monitor', 'blood-pressure-monitor-78', 'A simple upper-arm monitor with a large display, built for daily home checks.', 39.00, NULL, 8, 'seed-078.svg', 1),
(8, 'Collagen Peptides Powder', 'collagen-peptides-powder-79', 'Unflavored collagen that dissolves into coffee or smoothies without changing the taste.', 26.00, NULL, 12, 'seed-079.svg', 1),
(8, 'First Aid Kit - 120 Pieces', 'first-aid-kit-120-pieces-80', 'A well-stocked kit for home or car, organized in a compact zip case.', 23.00, NULL, 20, 'seed-080.svg', 1),
(9, 'Portable Car Jump Starter', 'portable-car-jump-starter-81', 'A pocket-sized jump starter with enough charge for multiple jumps, plus a USB port for phones.', 69.00, NULL, 18, 'seed-081.svg', 1),
(9, 'Memory Foam Seat Cushion', 'memory-foam-seat-cushion-82', 'Eases lower back strain on long drives, with a non-slip base that stays put.', 24.00, NULL, 40, 'seed-082.svg', 1),
(9, 'Car Phone Mount', 'car-phone-mount-83', 'A one-hand-operate mount that holds phones securely through potholes and turns.', 14.00, NULL, 40, 'seed-083.svg', 1),
(9, 'Microfiber Car Wash Kit', 'microfiber-car-wash-kit-84', 'Everything needed for a scratch-free wash at home, from mitt to drying towels.', 29.00, 37.17, 18, 'seed-084.svg', 1),
(9, 'Tire Pressure Gauge - Digital', 'tire-pressure-gauge-digital-85', 'A precise digital gauge that takes the guesswork out of tire checks.', 11.00, NULL, 25, 'seed-085.svg', 1),
(9, 'Dash Cam with Night Vision', 'dash-cam-with-night-vision-86', 'Records the road in sharp detail day or night, with loop recording and a wide field of view.', 79.00, NULL, 40, 'seed-086.svg', 1),
(9, 'Car Vacuum Cleaner - Handheld', 'car-vacuum-cleaner-handheld-87', 'A cordless handheld vacuum built specifically for cleaning up crumbs and dirt between seats.', 36.00, NULL, 8, 'seed-087.svg', 1),
(9, 'All-Weather Floor Mats', 'all-weather-floor-mats-88', 'Custom-molded mats that trap water, mud, and salt before it reaches the carpet.', 44.00, 57.01, 12, 'seed-088.svg', 1),
(9, 'Roof Cargo Carrier Bag', 'roof-cargo-carrier-bag-89', 'A waterproof bag that straps to any roof rack, adding extra space for road trips.', 59.00, NULL, 12, 'seed-089.svg', 1),
(9, 'Motorcycle Helmet - Full Face', 'motorcycle-helmet-full-face-90', 'DOT-certified protection with a quick-release visor and reinforced ventilation.', 129.00, NULL, 18, 'seed-090.svg', 1),
(10, 'Orthopedic Dog Bed', 'orthopedic-dog-bed-91', 'Supportive memory foam that eases pressure on joints, with a removable washable cover.', 54.00, NULL, 15, 'seed-091.svg', 1),
(10, 'Automatic Pet Feeder', 'automatic-pet-feeder-92', 'Programmable portion control keeps feeding times consistent, even when you''re not home.', 49.00, NULL, 20, 'seed-092.svg', 1),
(10, 'Cat Scratching Post Tower', 'cat-scratching-post-tower-93', 'A multi-level tower with sisal posts and a cozy perch, built to survive daily claws.', 44.00, NULL, 12, 'seed-093.svg', 1),
(10, 'Retractable Dog Leash', 'retractable-dog-leash-94', 'A smooth-braking retractable leash rated for dogs up to 110 lbs.', 19.00, 24.33, 50, 'seed-094.svg', 1),
(10, 'Interactive Cat Toy Wand', 'interactive-cat-toy-wand-95', 'A feather-and-bell wand that turns five minutes of play into real exercise.', 9.00, NULL, 50, 'seed-095.svg', 1),
(10, 'Pet Grooming Brush', 'pet-grooming-brush-96', 'A gentle deshedding brush that removes loose fur without irritating the skin.', 14.00, NULL, 12, 'seed-096.svg', 1),
(10, 'Stainless Steel Pet Bowls (Set of 2)', 'stainless-steel-pet-bowls-set-of-2-97', 'Rust-resistant bowls with a non-slip base, sized for cats and small dogs.', 16.00, 19.95, 18, 'seed-097.svg', 1),
(10, 'Dog Training Treats - Grain Free', 'dog-training-treats-grain-free-98', 'Small, low-calorie training treats that don''t derail a diet during long sessions.', 12.00, NULL, 18, 'seed-098.svg', 1),
(10, 'Aquarium LED Light Kit', 'aquarium-led-light-kit-99', 'Full-spectrum lighting that supports plant growth and shows off tank colors.', 27.00, 31.06, 8, 'seed-099.svg', 1),
(10, 'Bird Cage with Stand', 'bird-cage-with-stand-100', 'A roomy cage with multiple perches and an easy-clean sliding tray.', 89.00, NULL, 30, 'seed-100.svg', 1),
(11, 'Raised Garden Bed Kit', 'raised-garden-bed-kit-101', 'A modular cedar bed that assembles without tools, ready for a season of vegetables.', 79.00, NULL, 40, 'seed-101.svg', 1),
(11, 'Solar Pathway Lights (6-Pack)', 'solar-pathway-lights-6-pack-102', 'Auto-charging solar lights that line a walkway with a warm glow every night.', 32.00, NULL, 50, 'seed-102.svg', 1),
(11, 'Garden Tool Set (7-Piece)', 'garden-tool-set-7-piece-103', 'Rust-resistant hand tools with ergonomic grips, stored in a canvas carrying pouch.', 34.00, 41.12, 40, 'seed-103.svg', 1),
(11, 'Expandable Garden Hose 50ft', 'expandable-garden-hose-50ft-104', 'Contracts to a third of its length when the water''s off, easy to store and drag around.', 29.00, NULL, 8, 'seed-104.svg', 1),
(11, 'Outdoor String Lights', 'outdoor-string-lights-105', 'Weatherproof bulbs on a durable cord, built for patios and backyard evenings.', 24.00, 29.11, 50, 'seed-105.svg', 1),
(11, 'Compost Bin - Tumbling', 'compost-bin-tumbling-106', 'A dual-chamber tumbler that speeds up composting with an easy hand-crank turn.', 89.00, NULL, 8, 'seed-106.svg', 1),
(11, 'Patio Umbrella with Tilt', 'patio-umbrella-with-tilt-107', 'A wind-resistant umbrella that tilts to follow the sun through the afternoon.', 69.00, NULL, 50, 'seed-107.svg', 1),
(11, 'Bird Feeder - Squirrel Proof', 'bird-feeder-squirrel-proof-108', 'A weighted perch design that closes off seed access when a squirrel climbs on.', 26.00, 34.90, 50, 'seed-108.svg', 1),
(11, 'Folding Camping Chair', 'folding-camping-chair-109', 'A compact chair with a built-in cup holder, packed down small enough for any trunk.', 22.00, NULL, 12, 'seed-109.svg', 1),
(11, 'Portable Charcoal Grill', 'portable-charcoal-grill-110', 'A tabletop grill built for balconies and tailgates, with a lid that locks in smoke flavor.', 44.00, NULL, 12, 'seed-110.svg', 1),
(12, 'Single-Origin Coffee Beans 1lb', 'single-origin-coffee-beans-1lb-111', 'Medium-roast beans from a single farm, with tasting notes of chocolate and citrus.', 16.00, NULL, 18, 'seed-111.svg', 1),
(12, 'Herbal Tea Sampler (12 Flavors)', 'herbal-tea-sampler-12-flavors-112', 'A tin of twelve caffeine-free blends, a new one to try each morning.', 18.00, NULL, 18, 'seed-112.svg', 1),
(12, 'Raw Honey - Wildflower 16oz', 'raw-honey-wildflower-16oz-113', 'Unfiltered honey harvested from wildflower fields, never heat-processed.', 12.00, NULL, 8, 'seed-113.svg', 1),
(12, 'Extra Virgin Olive Oil 500ml', 'extra-virgin-olive-oil-500ml-114', 'Cold-pressed and bottled within a day of harvest, with a peppery finish.', 15.00, NULL, 30, 'seed-114.svg', 1),
(12, 'Dark Chocolate Bar Collection', 'dark-chocolate-bar-collection-115', 'Six single-origin bars ranging from 70% to 90% cacao, boxed for gifting.', 22.00, NULL, 50, 'seed-115.svg', 1),
(12, 'Organic Trail Mix 2lb', 'organic-trail-mix-2lb-116', 'A no-added-sugar mix of nuts, seeds, and dried fruit for the trail or the desk drawer.', 14.00, NULL, 20, 'seed-116.svg', 1),
(12, 'Sparkling Water Variety Pack', 'sparkling-water-variety-pack-117', 'Twelve cans across four fruit flavors, unsweetened and lightly carbonated.', 11.00, NULL, 25, 'seed-117.svg', 1),
(12, 'Gourmet Pasta Sauce Set', 'gourmet-pasta-sauce-set-118', 'Three small-batch sauces made with San Marzano tomatoes and slow-cooked aromatics.', 19.00, 24.30, 30, 'seed-118.svg', 1),
(12, 'Cold Brew Coffee Concentrate', 'cold-brew-coffee-concentrate-119', 'Steeped for 18 hours for a smooth, low-acid concentrate that mixes with water or milk.', 13.00, NULL, 40, 'seed-119.svg', 1),
(12, 'Spice Rack Starter Set (12 Jars)', 'spice-rack-starter-set-12-jars-120', 'Twelve essential spices in matching jars, labeled and ready for the rack.', 24.00, 30.58, 12, 'seed-120.svg', 1);

INSERT INTO settings (`key`, `value`) VALUES
    ('site_name', 'My Store'),
    ('currency_symbol', '$');

-- Sample reviews (user_id 2 = Test Customer) on a handful of products
INSERT INTO reviews (product_id, user_id, rating, comment) VALUES
(1, 2, 5, 'Exactly as described, would buy again.'),
(4, 2, 4, 'Good value for the price, works well.'),
(15, 2, 5, 'Better quality than I expected.'),
(32, 2, 3, 'Does the job but nothing special.'),
(47, 2, 5, 'Fast shipping and great packaging.'),
(61, 2, 4, 'Solid everyday item, happy with it.'),
(78, 2, 5, 'Exactly as described, would buy again.'),
(90, 2, 4, 'Good value for the price, works well.');
